"""update 

Revision ID: 00b5596068b3
Revises: d5b03ae43989
Create Date: 2026-02-17 17:37:51.626411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b5596068b3'
down_revision = 'd5b03ae43989'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
