"""product table update

Revision ID: 27994b24e916
Revises: 9097776ae6ef
Create Date: 2026-02-28 20:31:39.827272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27994b24e916'
down_revision = '9097776ae6ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
