"""product table update

Revision ID: 9097776ae6ef
Revises: 505aa37d4814
Create Date: 2026-02-28 20:27:41.606940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9097776ae6ef'
down_revision = '505aa37d4814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
