"""update 

Revision ID: d5b03ae43989
Revises: 002
Create Date: 2026-02-17 17:17:28.301445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b03ae43989'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('photo', sa.String(), nullable=True))
    op.drop_column('categories', 'picture')
    op.add_column('products', sa.Column('short_description', sa.String(), nullable=True))
    op.alter_column('products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('users', 'phone_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone')
    op.alter_column('products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('products', 'short_description')
    op.add_column('categories', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'photo')
    # ### end Alembic commands ###
